{
 "title": "Backups and Restores",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Backups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backup Creation Duration (log scale)",
   "type": "timeseries",
   "description": "The p50, p95, p99 and p100 of the durations of backup creations started in the last 24 hours OR still ongoing in logarithmic scale.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(1, spanner_backup_slo_creation_duration{job=\"spanner\"})",
     "legendFormat": "p100"
    },
    {
     "expr": "quantile(0.99, spanner_backup_slo_creation_duration{job=\"spanner\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile(0.95, spanner_backup_slo_creation_duration{job=\"spanner\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile(0.5, spanner_backup_slo_creation_duration{job=\"spanner\"})",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Count of Backup Creations per execution state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "count(spanner_backup_slo_creation_duration{job=\"spanner\"}) by (op_exec_state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ratio of Backup Creations within deadline",
   "type": "timeseries",
   "description": "The ratio of backups that started in the last week and completed within the estimated deadline.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg(spanner_backup_slo_backup_creations_within_deadline_rate{job=\"spanner\"})",
     "legendFormat": "ratio"
    }
   ]
  },
  { "title": "Restores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Restore Duration (log scale)",
   "type": "timeseries",
   "description": "The p50, p95, p99 and p100 of the durations of restores started in the last 24 hours OR still ongoing in logarithmic scale.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(1, spanner_backup_slo_restore_duration{job=\"spanner\"})",
     "legendFormat": "p100"
    },
    {
     "expr": "quantile(0.99, spanner_backup_slo_restore_duration{job=\"spanner\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile(0.95, spanner_backup_slo_restore_duration{job=\"spanner\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile(0.5, spanner_backup_slo_restore_duration{job=\"spanner\"})",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Count of Restores per execution state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "count(spanner_backup_slo_restore_duration{job=\"spanner\"}) by (op_exec_state)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}