{
 "title": "Compactions",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Successful/Failed Compactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Successful Compactions Per Compaction Type (Last 1h)",
   "type": "timeseries",
   "description": "Successful Compactions Per Compaction Type for last 1 hour.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(compact_type) (increase(spanner_server_compactions{job=\"spanner\", success=\"1\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Compactions Per Server (Last 1h)",
   "type": "timeseries",
   "description": "Successful Compactions Per Server for last 1 hour.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(spanner_server) (increase(spanner_server_compactions{job=\"spanner\", success=\"1\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Compactions Per Compaction Type (Last 1h)",
   "type": "timeseries",
   "description": "Failed Compactions Per Compaction Type for last 1 hour.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(compact_type) (increase(spanner_server_compactions{job=\"spanner\", success=\"0\", bad_error=\"1\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Compactions Per Server (Last 1h)",
   "type": "timeseries",
   "description": "Failed Compactions Per Server for last 1 hour.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(spanner_server) (increase(spanner_server_compactions{job=\"spanner\", bad_error=\"1\", success=\"0\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compactions Input/Output Bytes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compactions Output Bytes Rate Per Compaction Type",
     "type": "timeseries",
     "description": "Compaction output bytes rate  Per Compaction Type calculated over a 2 minute interval",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(compact_type) (rate(spanner_server_compaction_fs_output_bytes{job=\"spanner\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Compactions Output Bytes Rate Per Server",
     "type": "timeseries",
     "description": "Compaction output bytes rate  per server calculated over a 2 minute interval",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(spanner_server) (rate(spanner_server_compaction_fs_output_bytes{job=\"spanner\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Compactions Input Size (Mean) Per Compaction Type",
     "type": "timeseries",
     "description": "Mean of compaction input size per compaction type",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(compact_type) (delta(spanner_server_compaction_input_bytes_sum{job=\"spanner\"}[2m])) / sum by(compact_type) (delta(spanner_server_compaction_input_bytes_count{job=\"spanner\"}[2m]))",
       "legendFormat": "{{compact_type}}"
      }
     ]
    },
    {
     "title": "Compactions Input Size (Mean) Per Server",
     "type": "timeseries",
     "description": "Mean of compaction input size per server",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(spanner_server) (delta(spanner_server_compaction_input_bytes_sum{job=\"spanner\"}[2m])) / sum by(spanner_server) (delta(spanner_server_compaction_input_bytes_count{job=\"spanner\"}[2m]))",
       "legendFormat": "{{compact_type}}"
      }
     ]
    },
    {
     "title": "Compactions Input Size(P50 Estimate) Per Compaction Type",
     "type": "timeseries",
     "description": "P50 Estimate of compaction input size  per compaction type.\nThe percentile value is not exact but an approximation derived from the histogram metric assuming uniform distribution within a histogram bucket.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, compact_type) (delta(spanner_server_compaction_input_bytes_bucket{job=\"spanner\"}[2m])))",
       "legendFormat": "{{compact_type}}"
      }
     ]
    },
    {
     "title": "Compactions Input Size (P50 Estimate) Per Server",
     "type": "timeseries",
     "description": "P50 estimate of compaction input size per server.\nThe percentile value is not exact but an approximation derived from the histogram metric assuming uniform distribution within a histogram bucket.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, spanner_server) (delta(spanner_server_compaction_input_bytes_bucket{job=\"spanner\"}[2m])))",
       "legendFormat": "{{compact_type}}"
      }
     ]
    },
    {
     "title": "Compactions Input Size(P95 Estimate) Per Compaction Type",
     "type": "timeseries",
     "description": "P95 of compaction input size per compaction type.\nThe percentile value is not exact but an approximation derived from the histogram metric assuming uniform distribution within a histogram bucket.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, compact_type) (delta(spanner_server_compaction_input_bytes_bucket{job=\"spanner\"}[2m])))",
       "legendFormat": "{{compact_type}}"
      }
     ]
    },
    {
     "title": "Compactions Input Size(P95 Estimate) Per Server",
     "type": "timeseries",
     "description": "P95 estimate of compaction input size per server.\nThe percentile value is not exact but an approximation derived from the histogram metric assuming uniform distribution within a histogram bucket.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, spanner_server) (delta(spanner_server_compaction_input_bytes_bucket{job=\"spanner\"}[2m])))",
       "legendFormat": "{{compact_type}}"
      }
     ]
    },
    {
     "title": "Compactions Input Size(P99 Estimate) Per Compaction Type",
     "type": "timeseries",
     "description": "P99 Estimate of compaction input size per compaction type.\nThe percentile value is not exact but an approximation derived from the histogram metric assuming uniform distribution within a histogram bucket.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, compact_type) (delta(spanner_server_compaction_input_bytes_bucket{job=\"spanner\"}[2m])))",
       "legendFormat": "{{compact_type}}"
      }
     ]
    },
    {
     "title": "Compactions Input Size(P99 Estimate) Per Server",
     "type": "timeseries",
     "description": "P99 Estimate of compaction input size per server.\nThe percentile value is not exact but an approximation derived from the histogram metric assuming uniform distribution within a histogram bucket.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, spanner_server) (delta(spanner_server_compaction_input_bytes_bucket{job=\"spanner\"}[2m])))",
       "legendFormat": "{{compact_type}}"
      }
     ]
    }
   ]
  },
  { "title": "Major Compaction Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Major Compaction Lag (P50 Estimate) Per Server",
   "type": "timeseries",
   "description": "P50 Estimate of major compaction lag per server.\nThe percentile value is not exact but an approximation derived from the histogram metric assuming uniform distribution within a histogram bucket.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, spanner_server) (last_over_time(spanner_server_major_compaction_lag_distribution_bucket{job=\"spanner\"}[6m])))",
     "legendFormat": "{{compact_type}}"
    }
   ]
  },
  {
   "title": "Major Compaction Lag (P90 Estimate) Per Server",
   "type": "timeseries",
   "description": "P90 Estimate of major compaction lag per server.\nThe percentile value is not exact but an approximation derived from the histogram metric assuming uniform distribution within a histogram bucket.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, spanner_server) (last_over_time(spanner_server_major_compaction_lag_distribution_bucket{job=\"spanner\"}[6m])))",
     "legendFormat": "{{compact_type}}"
    }
   ]
  },
  {
   "title": "Major Compaction Lag (P99 Estimate) Per Server",
   "type": "timeseries",
   "description": "P99 Estimate of major compaction lag per server.\nThe percentile value is not exact but an approximation derived from the histogram metric assuming uniform distribution within a histogram bucket.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, spanner_server) (last_over_time(spanner_server_major_compaction_lag_distribution_bucket{job=\"spanner\"}[6m])))",
     "legendFormat": "{{compact_type}}"
    }
   ]
  }
 ]
}