{
 "title": "Deployment Insights",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SpannerServer",
    "query": {
     "query": "label_values(up{job=\"spanner\"}, spanner_server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server Count By Version",
   "type": "timeseries",
   "description": "Number of servers running each Spanner binary, schema, and feature compatibility version",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by(binary_version_name, binary_version) (spanner_version_info{job=\"spanner\", spanner_server=~\"$SpannerServer\"})",
     "legendFormat": "Binary: {{binary_version_name}} ({{binary_version}})"
    },
    {
     "expr": "count by(schema_version) (spanner_version_info{job=\"spanner\", spanner_server=~\"$SpannerServer\"})",
     "legendFormat": "Schema: {{schema_version}}"
    },
    {
     "expr": "count by(feature_version) (spanner_version_info{job=\"spanner\", spanner_server=~\"$SpannerServer\"})",
     "legendFormat": "Feature: {{feature_version}}"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "description": "Aggregated CPU utilization for the selected servers",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by() (rate(proc_cpu_usage{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval])) / sum by() (spanner_box_vm_cpu_total{job=\"spanner\", spanner_server=~\"$SpannerServer\"})",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "description": "Aggregated memory utilization for the selected servers.\nThe values here can be really high as spanner aggressively caches data in memory which can be freed if needed.",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by() (spanner_box_vm_memory_usage{job=\"spanner\", spanner_server=~\"$SpannerServer\"}) / sum by() (spanner_box_vm_memory_total{job=\"spanner\", spanner_server=~\"$SpannerServer\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Server CPU utilization",
   "type": "timeseries",
   "description": "CPU utilization for each selected server",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(spanner_server) (rate(proc_cpu_usage{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval])) / sum by(spanner_server) (spanner_box_vm_cpu_total{job=\"spanner\", spanner_server=~\"$SpannerServer\"})",
     "legendFormat": "{{spanner_server}}"
    }
   ]
  },
  {
   "title": "Server Memory utilization",
   "type": "timeseries",
   "description": "Memory utilization for each of the selected servers.\nThe values here can be really high as spanner aggressively caches data in memory which can be freed if needed.",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(spanner_server) (spanner_box_vm_memory_usage{job=\"spanner\", spanner_server=~\"$SpannerServer\"}) / sum by(spanner_server) (spanner_box_vm_memory_total{job=\"spanner\", spanner_server=~\"$SpannerServer\"})",
     "legendFormat": "{{spanner_server}}"
    }
   ]
  },
  {
   "title": "Process CPU utilization",
   "type": "timeseries",
   "description": "CPU utilization for each process aggregated across the selected servers",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(process) (rate(proc_cpu_usage{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval])) / ignoring(process) group_left() sum(spanner_box_vm_cpu_total{job=\"spanner\", spanner_server=~\"$SpannerServer\"})",
     "legendFormat": "{{spanner_server}}"
    }
   ]
  },
  {
   "title": "Server Memory Breakdown",
   "type": "timeseries",
   "description": "Memory utilization by category aggregated across the selected servers. This memory is specific to the span server process.",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(category) (spanner_server_memory_usage{job=\"spanner\", spanner_server=~\"$SpannerServer\", category=~\"cache|fragmented|memtable_pinned|system|updates|other\"})",
     "legendFormat": "{{spanner_server}}"
    }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "min by(spanner_server) (proc_uptime{job=\"spanner\", spanner_server=~\"$SpannerServer\", process=\"server\"})",
     "legendFormat": "{{spanner_server}}"
    }
   ]
  },
  {
   "title": "Process Virtual Memory Size",
   "type": "timeseries",
   "description": "Virtual memory size for each process for selected servers.",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(process) (proc_memory_virtual_size{job=\"spanner\", spanner_server=~\"$SpannerServer\"})",
     "legendFormat": "{{spanner_server}}"
    }
   ]
  },
  {
   "title": "Network Received Bytes",
   "type": "timeseries",
   "description": "Received bytes per interface aggregated across all servers",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(network_interface) (rate(spanner_box_vm_network_received_bytes{job=\"spanner\", spanner_server=~\"$SpannerServer\", network_interface=~\"eth.*|ens.*\"}[$__rate_interval]))",
     "legendFormat": "{{spanner_server}}"
    }
   ]
  },
  {
   "title": "Process Resident Memory Size",
   "type": "timeseries",
   "description": "Resident memory size for each process for selected servers.",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(process) (proc_memory_resident_size{job=\"spanner\", spanner_server=~\"$SpannerServer\"})",
     "legendFormat": "{{spanner_server}}"
    }
   ]
  },
  {
   "title": "Network Sent Bytes",
   "type": "timeseries",
   "description": "Sent bytes per interface aggregated across all servers",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(network_interface) (rate(spanner_box_vm_network_sent_bytes{job=\"spanner\", spanner_server=~\"$SpannerServer\", network_interface=~\"eth.*|ens.*\"}[$__rate_interval]))",
     "legendFormat": "{{spanner_server}}"
    }
   ]
  },
  {
   "title": "Top 10 Servers By Network Received Bytes",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum by(spanner_server) (rate(spanner_box_vm_network_received_bytes{job=\"spanner\", spanner_server=~\"$SpannerServer\", network_interface=~\"eth.*|ens.*\"}[$__rate_interval])))",
     "legendFormat": "{{spanner_server}}"
    }
   ]
  },
  {
   "title": "Top 10 Servers By Network Sent Bytes",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum by(spanner_server) (rate(spanner_box_vm_network_sent_bytes{job=\"spanner\", spanner_server=~\"$SpannerServer\", network_interface=~\"eth.*|ens.*\"}[$__rate_interval])))",
     "legendFormat": "{{spanner_server}}"
    }
   ]
  }
 ]
}