{
 "title": "gRPC",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SpannerServer",
    "query": {
     "query": "label_values(up{job=\"spanner\"}, spanner_server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server Side Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "P50 RPC Latency Per Method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, command) (increase(server_rpc_latency_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval])))",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "P90 RPC Latency Per Method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by(le, command) (increase(server_rpc_latency_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval])))",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "P99 RPC Latency Per Method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, command) (increase(server_rpc_latency_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval])))",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "Server Sent Throughput Per Method",
     "type": "timeseries",
     "description": "Sent bytes per sec per method for selected servers",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(command) (rate(server_sent_bytes_per_rpc_sum{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval]))",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "Server Sent Throughput Per Process",
     "type": "timeseries",
     "description": "Sent bytes per sec per process for selected servers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(process) (rate(server_sent_bytes_per_rpc_sum{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval]))",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "Server Received Throughput Per Method",
     "type": "timeseries",
     "description": "Received bytes per sec per method for selected servers",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(command) (rate(server_received_bytes_per_rpc_sum{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Server Received Throughput Per Process",
     "type": "timeseries",
     "description": "Received bytes per sec per process for selected servers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(process) (rate(server_received_bytes_per_rpc_sum{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Server Canonical Status Count Per Method",
     "type": "timeseries",
     "description": "Rate of occurrence of canonical status code per method for selected servers",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum by(canonical_code, command) (rate(server_canonical_status_count{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval]))",
       "legendFormat": "{{command}} : {{canonical_code}}"
      }
     ]
    },
    {
     "title": "Server Completed RPCs Per Method",
     "type": "timeseries",
     "description": "Rate of completed RPCs per method for selected servers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "sum by(command) (rate(server_completed_rpcs{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Server Active Channels",
     "type": "timeseries",
     "description": "The total number of server-side gRPC channels created since application started, that have not been shut down.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum by(spanner_server) (server_active_channels{job=\"spanner\", spanner_server=~\"$SpannerServer\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Client Side Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "P50 Client Roundtrip Latency Per Method",
     "type": "timeseries",
     "description": "P50 of round trip RPC latency per method (which includes server latency and network/queue time) as measured by grpc client for selected servers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, command) (increase(client_roundtrip_latency_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval])))",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "P90 Client Roundtrip Latency Per Method",
     "type": "timeseries",
     "description": "P90 of round trip RPC latency per method (which includes server latency and network/queue time) as measured by grpc client for selected servers.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by(le, command) (increase(client_roundtrip_latency_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval])))",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "P99 Client Roundtrip Latency Per Method",
     "type": "timeseries",
     "description": "P99 of round trip RPC latency per method (which includes server latency and network/queue time) as measured by grpc client for selected servers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, command) (increase(client_roundtrip_latency_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval])))",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "Client Sent Throughput Per Method",
     "type": "timeseries",
     "description": "Sent bytes per second per method for selected servers",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(command) (rate(client_sent_bytes_per_rpc_sum{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Client Sent Throughput Per Process",
     "type": "timeseries",
     "description": "Sent bytes per second per process for selected servers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(process) (rate(client_sent_bytes_per_rpc_sum{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Client Received Throughput Per Method",
     "type": "timeseries",
     "description": "Received bytes per second per method for selected servers",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(command) (rate(client_received_bytes_per_rpc_sum{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Client Received Throughput Per Process",
     "type": "timeseries",
     "description": "Received bytes per second per process for selected servers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(process) (rate(client_received_bytes_per_rpc_sum{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Client Canonical Status Count Per Method",
     "type": "timeseries",
     "description": "Rate of occurrence of canonical status code per method as a grpc client for selected servers",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum by(canonical_code, command) (rate(client_canonical_status_count{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval]))",
       "legendFormat": "{{command}} : {{ canonical_code}}"
      }
     ]
    },
    {
     "title": "Client Completed RPCs Per Method",
     "type": "timeseries",
     "description": "Rate of completed client RPCs per method for selected servers.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum by(command) (rate(client_completed_rpcs{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}