{
 "title": "Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Active Alerts & System Concerns",
   "type": "alertlist",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Compute Capacity (vCPU)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spanner_box_vm_cpu_total{job=\"spanner\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spanner_box_vm_memory_total{job=\"spanner\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(filesystem_size{job=\"spanner\", type=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(filesystem_size{job=\"spanner\", type=\"available\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (spanner_server) (last_over_time(proc_uptime{job=\"spanner\"}[30s]) and on(spanner_server) up{job=\"spanner\"}))",
     "legendFormat": "Healthy"
    },
    {
     "expr": "count(group by (spanner_server) (up{job=\"spanner\"}))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Compute Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(proc_cpu_usage{job=\"spanner\"}[$__rate_interval])) / sum(last_over_time(spanner_box_vm_cpu_total{job=\"spanner\"}[20s]))",
     "legendFormat": "CPU Utilization"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "description": "Total memory usage across the deployment. It is expected to see high memory usage values as spanner tries to aggressively use idle memory for cache purposes.",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spanner_box_vm_memory_usage{job=\"spanner\"}) / sum(spanner_box_vm_memory_total{job=\"spanner\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(filesystem_size{job=\"spanner\", type=\"used\"}) / sum(filesystem_size{job=\"spanner\", type=\"total\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Used Per vCPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(filesystem_size{job=\"spanner\", type=\"used\"}) / sum(spanner_box_vm_cpu_total{job=\"spanner\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Healthy Servers",
   "type": "table",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(spanner_server, spanner_zone) (rate(proc_cpu_usage{job=\"spanner\"}[$__rate_interval])) / sum by(spanner_server, spanner_zone) (spanner_box_vm_cpu_total{job=\"spanner\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(spanner_server, spanner_zone) (spanner_box_vm_memory_usage{job=\"spanner\"}) / sum by(spanner_server, spanner_zone) (spanner_box_vm_memory_total{job=\"spanner\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(spanner_server, spanner_zone) (last_over_time(proc_uptime{job=\"spanner\", process=\"server\"}[30s]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(spanner_server, spanner_zone) (spanner_box_vm_cpu_total{job=\"spanner\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(spanner_server, spanner_zone) (spanner_box_vm_memory_total{job=\"spanner\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(spanner_server, spanner_zone) (filesystem_size{job=\"spanner\", type=\"used\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(spanner_server, spanner_zone) (filesystem_size{job=\"spanner\", type=\"total\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy Servers",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (spanner_server) (up{job=\"spanner\"} unless on(spanner_server) last_over_time(proc_uptime{job=\"spanner\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}