{
 "title": "Shared Log",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SpannerServer",
    "query": {
     "query": "label_values(up{job=\"spanner\"}, spanner_server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Shared Log Write Rate",
   "type": "timeseries",
   "description": "Shared log count per sec aggregated across selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(spanner_sharedlog_log_entries{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[10m]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Shared Log Write Rate Per Database",
   "type": "timeseries",
   "description": "Shared log count per sec per database aggregated across selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(database) (rate(spanner_sharedlog_log_entries{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[10m]))",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Shared Log Bytes Written",
   "type": "timeseries",
   "description": "Shared log bytes written per sec aggregated across selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(spanner_sharedlog_bytes_written{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[10m]))",
     "legendFormat": "Shared Log Write Throughput"
    }
   ]
  },
  {
   "title": "Shared Log Bytes Written Per Database",
   "type": "timeseries",
   "description": "Shared log bytes written per sec per database aggregated across selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(database) (rate(spanner_sharedlog_bytes_written{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[10m]))",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Shared Log Batches Write Rate",
   "type": "timeseries",
   "description": "Shared log batches written per sec aggregated across selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(spanner_sharedlog_log_batches{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[10m]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Shared Log Batch Write Latency Distribution",
   "type": "timeseries",
   "description": "Shared log batch write latency distribution aggregated across selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (delta(spanner_sharedlog_write_batch_latency_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[10m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (delta(spanner_sharedlog_write_batch_latency_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[10m])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (delta(spanner_sharedlog_write_batch_latency_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[10m])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Shared Log Batch Entries Count Distribution",
   "type": "timeseries",
   "description": "Distribution of entries count in shared log batches aggregated across selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (delta(spanner_sharedlog_log_batch_num_entries_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[10m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "sum by(le) (histogram_quantile(0.9, delta(spanner_sharedlog_log_batch_num_entries_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[10m])))",
     "legendFormat": "P90"
    },
    {
     "expr": "sum by(le) (histogram_quantile(0.99, delta(spanner_sharedlog_log_batch_num_entries_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[10m])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "LogSort Request Rate",
   "type": "timeseries",
   "description": "LogSort request rate aggregated across selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(spanner_server_logsort_requests{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[10m]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "LogSort Sorting Error Rate",
   "type": "timeseries",
   "description": "LogSort sorting error rate aggregated across selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(spanner_server_logsort_sorting_errors{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[10m]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "In Progress Shared Log Readers",
   "type": "timeseries",
   "description": "The number of shared log readers that are currently recovering tablets.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(last_over_time(spanner_sharedlog_inprogress_log_readers{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[6m]))",
     "legendFormat": "Rate"
    }
   ]
  }
 ]
}