{
 "title": "Spanner Filesystem",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "File Operation Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(operation) (rate(filesystem_canonical_status_count{job=\"spanner\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Local/Remote Operations Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(type) (rate(filesystem_canonical_status_count{job=\"spanner\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Operation Errors Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(operation, status) (rate(filesystem_canonical_status_count{job=\"spanner\", status!=\"OK\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Local Operations P50 Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, operation) (delta(filesystem_latency_bucket{job=\"spanner\", type=\"LOCAL\"}[$__interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Remote Operations P50 Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, operation) (delta(filesystem_latency_bucket{job=\"spanner\", type=\"REMOTE\"}[$__interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Local Operations P90 Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by(le, operation) (delta(filesystem_latency_bucket{job=\"spanner\", type=\"LOCAL\"}[$__interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Remote Operations P90 Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by(le, operation) (delta(filesystem_latency_bucket{job=\"spanner\", type=\"REMOTE\"}[$__interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Local Operations P99 Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, operation) (delta(filesystem_latency_bucket{job=\"spanner\", type=\"LOCAL\"}[$__interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Remote Operations P99 Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, operation) (delta(filesystem_latency_bucket{job=\"spanner\", type=\"REMOTE\"}[$__interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Local Read/Write Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(operation) (rate(filesystem_throughput_sum{job=\"spanner\", type=\"LOCAL\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Remote Read/Write Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(operation) (rate(filesystem_throughput_sum{job=\"spanner\", type=\"REMOTE\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Bytes Per Local Operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, operation) (delta(filesystem_throughput_bucket{job=\"spanner\", type=\"LOCAL\"}[$__interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P50 Bytes Per Remote Operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le, operation) (delta(filesystem_throughput_bucket{job=\"spanner\", type=\"REMOTE\"}[$__interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P90 Bytes Per Local Operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by(le, operation) (delta(filesystem_throughput_bucket{job=\"spanner\", type=\"LOCAL\"}[$__interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P90 Bytes Per Remote Operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by(le, operation) (delta(filesystem_throughput_bucket{job=\"spanner\", type=\"REMOTE\"}[$__interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem Usage By Zone",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "sum by(spanner_zone) (filesystem_size{job=\"spanner\", type=\"used\"}) * on(spanner_zone) group_left(capacity_gib) count_values by(spanner_zone) (\"capacity_gib\", round(sum by(spanner_zone) (filesystem_size{job=\"spanner\", type=\"total\"} @ end()) / 1024))",
       "legendFormat": "{{spanner_zone}}  [Capacity: {{capacity_gib}} GiB]"
      }
     ]
    },
    {
     "title": "Top 10 Servers By Filesystem Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "(sum by(spanner_server) (filesystem_size{job=\"spanner\", type=\"used\"}) and on(spanner_server) topk(10, max_over_time(sum by(spanner_server) (filesystem_size{job=\"spanner\", type=\"used\"})[$__range:] @ end()))) * on(spanner_server) group_left(capacity_gib) count_values by(spanner_server) (\"capacity_gib\", round(sum by(spanner_server) (filesystem_size{job=\"spanner\", type=\"total\"} @ end()) / 1024))",
       "legendFormat": "{{spanner_server}}  [Capacity: {{capacity_gib}} GiB]"
      }
     ]
    }
   ]
  }
 ]
}