{
 "title": "Splits Merges Moves",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SpannerServer",
    "query": {
     "query": "label_values(up{job=\"spanner\"}, spanner_server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Split size Distribution",
   "type": "timeseries",
   "description": "Size of the directory split, in bytes aggregated across selected servers\nThe percentile value is not exact but an approximation derived from the histogram metric assuming uniform distribution within a histogram bucket.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (last_over_time(spanner_server_split_total_bytes_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[6m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (last_over_time(spanner_server_split_total_bytes_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[6m])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (last_over_time(spanner_server_split_total_bytes_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[6m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (last_over_time(spanner_server_split_total_bytes_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[6m])))",
     "legendFormat": "P100"
    }
   ]
  },
  {
   "title": "Group Size Distribution",
   "type": "timeseries",
   "description": "All bytes allocated for the group including persistent and in memory data structures aggregated across selected servers\nThe percentile value is not exact but an approximation derived from the histogram metric assuming uniform distribution within a histogram bucket.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (spanner_server_group_size_bucket{job=\"spanner\", media=\"total\", spanner_server=~\"$SpannerServer\"}))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (spanner_server_group_size_bucket{job=\"spanner\", media=\"total\", spanner_server=~\"$SpannerServer\"}))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (spanner_server_group_size_bucket{job=\"spanner\", media=\"total\", spanner_server=~\"$SpannerServer\"}))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (spanner_server_group_size_bucket{job=\"spanner\", media=\"total\", spanner_server=~\"$SpannerServer\"}))",
     "legendFormat": "P100"
    }
   ]
  },
  {
   "title": "Group Size In Memory Distribution",
   "type": "timeseries",
   "description": "All bytes allocated for the group in memory data structures aggregated across selected servers\nThe percentile value is not exact but an approximation derived from the histogram metric assuming uniform distribution within a histogram bucket.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (spanner_server_group_size_bucket{job=\"spanner\", media=\"ram\", spanner_server=~\"$SpannerServer\"}))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (spanner_server_group_size_bucket{job=\"spanner\", media=\"ram\", spanner_server=~\"$SpannerServer\"}))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (spanner_server_group_size_bucket{job=\"spanner\", media=\"ram\", spanner_server=~\"$SpannerServer\"}))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (spanner_server_group_size_bucket{job=\"spanner\", media=\"ram\", spanner_server=~\"$SpannerServer\"}))",
     "legendFormat": "P100"
    }
   ]
  },
  {
   "title": "Group Size P50 By Zone ",
   "type": "timeseries",
   "description": "All bytes allocated for the group including persistent and in memory data structures for each zone.\nThe percentile value is not exact but an approximation derived from the histogram metric assuming uniform distribution within a histogram bucket.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, spanner_zone) (spanner_server_group_size_bucket{job=\"spanner\", media=\"total\"}))",
     "legendFormat": "{{spanner_zone}}"
    }
   ]
  },
  {
   "title": "Group Size P90 By Zone ",
   "type": "timeseries",
   "description": "All bytes allocated for the group including persistent and in memory data structures for each zone\nThe percentile value is not exact but an approximation derived from the histogram metric assuming uniform distribution within a histogram bucket.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, spanner_zone) (spanner_server_group_size_bucket{job=\"spanner\", media=\"total\"}))",
     "legendFormat": "{{spanner_zone}}"
    }
   ]
  },
  {
   "title": "Group Size P99 By Zone ",
   "type": "timeseries",
   "description": "All bytes allocated for the group including persistent and in memory data structures for each zone.\nThe percentile value is not exact but an approximation derived from the histogram metric assuming uniform distribution within a histogram bucket.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, spanner_zone) (spanner_server_group_size_bucket{job=\"spanner\", media=\"total\"}))",
     "legendFormat": "{{spanner_zone}}"
    }
   ]
  },
  {
   "title": "Group Size P100 By Zone ",
   "type": "timeseries",
   "description": "All bytes allocated for the group including persistent and in memory data structures for each zone.\nThe percentile value is not exact but an approximation derived from the histogram metric assuming uniform distribution within a histogram bucket.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le, spanner_zone) (spanner_server_group_size_bucket{job=\"spanner\", media=\"total\"}))",
     "legendFormat": "{{spanner_zone}}"
    }
   ]
  },
  {
   "title": "Number of successful internal data moves",
   "type": "timeseries",
   "description": "Number of Directory and Group Moves, Splits, and Merges Over 1 hour Sliding Window By Initiator, Action And Move Type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(initiator, action, move_type) (increase(spanner_server_movedir_types{job=\"spanner\"}[1h]))",
     "legendFormat": "{{initiator}} {{ action}} {{move_type}}"
    }
   ]
  },
  {
   "title": "Number of failed internal data moves",
   "type": "timeseries",
   "description": "Number of Errors in Attempted Directory and Group Moves, Splits, and Merges over 1h sliding window per action, initiator, Borg Cell\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(initiator, action, move_type) (increase(spanner_server_movedir_errors{job=\"spanner\"}[1h]))",
     "legendFormat": "{{initiator}} {{ action}} {{move_type}}"
    }
   ]
  },
  {
   "title": "Unsplittable errors by reason and type",
   "type": "timeseries",
   "description": "Rate of unsplittable errors which is the number of overloaded splits ignored by the directory splitter since target range was detected to be unsplittable",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(reason, type, database) (increase(spanner_server_unsplittable_errors{job=\"spanner\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peak Split CPU Usage Score",
   "type": "timeseries",
   "description": "The max cpu usage across all splits of each database. Score above 50 represents warm splits, whereas score of 100 represents hot splits",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by (database) (\n  clamp_max(\n    (\n      sum by(database, spanner_server) (spanner_hottest_key_range_usage{job=\"spanner\", spanner_server=~\"$SpannerServer\"})\n      / on(spanner_server) group_left \n      \n      clamp_max(sum by(spanner_server) (spanner_available_milligcu{job=\"spanner\", spanner_server=~\"$SpannerServer\"}), 7000)\n    ) * 100, \n    100\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}