{
 "title": "System Insights",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SpannerServer",
    "query": {
     "query": "label_values(up{job=\"spanner\"}, spanner_server)"
    }
   },
   {
    "name": "Database",
    "query": {
     "query": "label_values(spanner_cpu_utilization_by_priority_and_category{job=\"spanner\"},database)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization Overview",
   "type": "timeseries",
   "description": "Database overall CPU utilization aggregated across selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by() (spanner_cpu_utilization_by_priority_and_category{job=\"spanner\", spanner_server=~\"$SpannerServer\", database=~\"$Database\"}) * 100) / ignoring(database) group_left() sum(spanner_available_milligcu{job=\"spanner\", spanner_server=~\"$SpannerServer\"})",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "CPU utilization by user/system",
   "type": "timeseries",
   "description": "Utilization of CPU in the selected database, grouped by User/System tasks and priority. The utilization is aggregated across the selected servers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(priority, is_system) (spanner_cpu_utilization_by_priority_and_category{job=\"spanner\", spanner_server=~\"$SpannerServer\", database=~\"$Database\"}) * 100) / ignoring(priority, is_system) group_left() sum(spanner_available_milligcu{job=\"spanner\", spanner_server=~\"$SpannerServer\"})",
     "legendFormat": "{{priority}} - System: {{is_system}}"
    }
   ]
  },
  {
   "title": "CPU Utilization By Operation Type",
   "type": "timeseries",
   "description": "Utilization of CPU grouped by operation type for the selected database aggregated across the selected servers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(category) (spanner_cpu_utilization_by_priority_and_category{job=\"spanner\", database=~\"$Database\", spanner_server=~\"$SpannerServer\"}) * 100) / ignoring(category) group_left() sum(spanner_available_milligcu{job=\"spanner\", spanner_server=~\"$SpannerServer\"})",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "CPU Utilization By Operation Type - High Priority",
   "type": "timeseries",
   "description": "Utilization of CPU grouped by operation type and filtered by high priority for the selected database aggregated across the selected servers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(category) (spanner_cpu_utilization_by_priority_and_category{job=\"spanner\", priority=\"high\", database=~\"$Database\", spanner_server=~\"$SpannerServer\"}) * 100) / ignoring(category) group_left() sum(spanner_available_milligcu{job=\"spanner\", spanner_server=~\"$SpannerServer\"})",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "CPU Utilization By Operation Type - Medium Priority",
   "type": "timeseries",
   "description": "Utilization of CPU grouped by operation type and filtered by medium priority for the selected database aggregated across the selected servers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(category) (spanner_cpu_utilization_by_priority_and_category{job=\"spanner\", priority=\"medium\", database=~\"$Database\", spanner_server=~\"$SpannerServer\"}) * 100) / ignoring(category) group_left() sum(spanner_available_milligcu{job=\"spanner\", spanner_server=~\"$SpannerServer\"})",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "CPU Utilization By Operation Type - Low Priority",
   "type": "timeseries",
   "description": "Utilization of CPU grouped by operation type and filtered by low priority for the selected database aggregated across the selected servers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(category) (spanner_cpu_utilization_by_priority_and_category{job=\"spanner\", priority=\"low\", database=~\"$Database\", spanner_server=~\"$SpannerServer\"}) * 100) / ignoring(category) group_left() sum(spanner_available_milligcu{job=\"spanner\", spanner_server=~\"$SpannerServer\"})",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Request Latency - P50",
   "type": "timeseries",
   "description": "P50 latency within a selected database, grouped by read/write methods across the selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (delta(spanner_api_request_latencies_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\", database=~\"$Database\", method=~\".*/ExecuteSql|.*/ExecuteStreamingSql|.*/Read|.*/StreamingRead\"}[1m])))",
     "legendFormat": "Read"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (delta(spanner_api_request_latencies_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\", database=~\"$Database\", method=~\".*/Commit|.*/BatchWrite|.*/ExecuteBatchDml\"}[1m])))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Request Latency - P90",
   "type": "timeseries",
   "description": "P90 latency within a selected database, grouped by read/write methods across the selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (delta(spanner_api_request_latencies_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\", database=~\"$Database\", method=~\".*/ExecuteSql|.*/ExecuteStreamingSql|.*/Read|.*/StreamingRead\"}[1m])))",
     "legendFormat": "Read"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (delta(spanner_api_request_latencies_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\", database=~\"$Database\", method=~\".*/Commit|.*/BatchWrite|.*/ExecuteBatchDml\"}[1m])))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Request Latency - P99",
   "type": "timeseries",
   "description": "P99 latency within a selected database, grouped by read/write methods across the selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (delta(spanner_api_request_latencies_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\", database=~\"$Database\", method=~\".*/ExecuteSql|.*/ExecuteStreamingSql|.*/Read|.*/StreamingRead\"}[1m])))",
     "legendFormat": "Read"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (delta(spanner_api_request_latencies_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\", database=~\"$Database\", method=~\".*/Commit|.*/BatchWrite|.*/ExecuteBatchDml\"}[1m])))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Request Latency By Method - P50",
   "type": "timeseries",
   "description": "P50 latency within a selected database, grouped by API methods across the selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.5, sum by(le, method) (delta(spanner_api_request_latencies_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\", database=~\"$Database\"}[1m]))), \"method\", \"${1}\", \"method\", \".*/(.*)\")",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Request Latency By Method - P90",
   "type": "timeseries",
   "description": "P90 latency within a selected database, grouped by API methods across the selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.9, sum by(le, method) (delta(spanner_api_request_latencies_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\", database=~\"$Database\"}[1m]))), \"method\", \"${1}\", \"method\", \".*/(.*)\")",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Request Latency By Method - P99",
   "type": "timeseries",
   "description": "P99 latency within a selected database, grouped by API methods across the selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.99, sum by(le, method) (delta(spanner_api_request_latencies_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\", database=~\"$Database\"}[1m]))), \"method\", \"$1\", \"method\", \".*/(.*)\")",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Transaction Latency - P50",
   "type": "timeseries",
   "description": "P50 request latency within a selected database, grouped by transaction type and leader involvement across the selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, transaction_type, is_leader_involved) (delta(spanner_api_request_latencies_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\", database=~\"$Database\", transaction_type!=\"NONE\"}[1m])))",
     "legendFormat": "{{transaction_type}} - is_leader_involved: {{is_leader_involved}}"
    }
   ]
  },
  {
   "title": "Transaction Latency - P90",
   "type": "timeseries",
   "description": "P90 request latency within a selected database, grouped by transaction type and leader involvement across the selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, transaction_type, is_leader_involved) (delta(spanner_api_request_latencies_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\", database=~\"$Database\", transaction_type!=\"NONE\"}[1m])))",
     "legendFormat": "{{transaction_type}} - is_leader_involved: {{is_leader_involved}}"
    }
   ]
  },
  {
   "title": "Transaction Latency - P99",
   "type": "timeseries",
   "description": "P99 request latency within a selected database, grouped by transaction type and leader involvement across the selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, transaction_type, is_leader_involved) (delta(spanner_api_request_latencies_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\", database=~\"$Database\", transaction_type!=\"NONE\"}[1m])))",
     "legendFormat": "{{transaction_type}} - is_leader_involved: {{is_leader_involved}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Read/Write Throughput within selected database across selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(spanner_throughput_reads{job=\"spanner\", spanner_server=~\"$SpannerServer\", database=~\"$Database\", method=~\".*/ExecuteSql|.*/ExecuteStreamingSql|.*/Read|.*/StreamingRead\"}[1m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(spanner_throughput_writes{job=\"spanner\", spanner_server=~\"$SpannerServer\", database=~\"$Database\", method=~\".*/Commit|.*/BatchWrite|.*/ExecuteBatchDml\"}[1m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Throughput By Method",
   "type": "timeseries",
   "description": "Throughput within selected database grouped by method across selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "label_replace(sum by(method) (rate(spanner_throughput_reads{job=\"spanner\", spanner_server=~\"$SpannerServer\", database=~\"$Database\"}[1m])), \"method\", \"$1\", \"method\", \".*/(.*)\")",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Operations Per Second",
   "type": "timeseries",
   "description": "Number of operations per second within selected database grouped by read/write methods across selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(spanner_api_request_count{job=\"spanner\", spanner_server=~\"$SpannerServer\", database=~\"$Database\", method=~\".*/ExecuteSql|.*/ExecuteStreamingSql|.*/Read|.*/StreamingRead\", status=\"OK\"}[1m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(spanner_api_request_count{job=\"spanner\", spanner_server=~\"$SpannerServer\", database=~\"$Database\", method=~\".*/Commit|.*/BatchWrite|.*/ExecuteBatchDml\", status=\"OK\"}[1m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Operations Per Second By Method",
   "type": "timeseries",
   "description": "Number of operations per second within selected database grouped by methods across selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(sum by(method) (rate(spanner_api_request_count{job=\"spanner\", spanner_server=~\"$SpannerServer\", database=~\"$Database\", status=\"OK\"}[1m])), \"method\", \"$1\", \"method\", \".*/(.*)\")",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Storage Utilization By Database",
   "type": "timeseries",
   "description": "Non replicated physical bytes used by each database.\nThis metric is coming from leader tablet of each group, the actual replicated physical bytes across all tablets of a  group might be higher/lower depending upon state of compactions on each tablet but this metric gives an approximate idea of how much non replicated physical storage is being used by each database.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(database) (spanner_server_group_size_sum{job=\"spanner\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Lock Wait Time",
   "type": "timeseries",
   "description": "Total lock wait time for lock conflicts for the selected database in a 5 minute interval",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by(database) (increase(spanner_total_lock_wait_time{job=\"spanner\", database=~\"$Database\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aborted Transactions Rate",
   "type": "timeseries",
   "description": "The rate of transactions that were aborted. Higher abort rates can occur when there are conflicts between transactions.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "sum by(database) (rate(spanner_transaction_stat_total_commit_attempt_count{job=\"spanner\", database=~\"$Database\", status=\"abort\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Schema Object Count",
   "type": "timeseries",
   "description": "Number of schema objects for the selected database",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "max by(database) (spanner_instance_schema_objects{job=\"spanner\", database=~\"$Database\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Participants",
   "type": "timeseries",
   "description": "Distribution of number of transaction participants in each commit attempt for the database",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, database) (delta(spanner_transaction_stat_total_participants_bucket{job=\"spanner\", database=~\"$Database\"}[2m])))",
     "legendFormat": "{{ database }} P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, database) (delta(spanner_transaction_stat_total_participants_bucket{job=\"spanner\", database=~\"$Database\"}[2m])))",
     "legendFormat": "{{database}} P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, database) (delta(spanner_transaction_stat_total_participants_bucket{job=\"spanner\", database=~\"$Database\"}[2m])))",
     "legendFormat": "{{database}} P99"
    }
   ]
  }
 ]
}