{
 "title": "Tablets",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SpannerServer",
    "query": {
     "query": "label_values(up{job=\"spanner\"}, spanner_server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Tablet Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(spanner_paxos_tablet_count{job=\"spanner\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Tablet Count By Zone",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(spanner_zone) (spanner_paxos_tablet_count{job=\"spanner\"})",
     "legendFormat": "{{spanner_zone}}"
    }
   ]
  },
  {
   "title": "Tablet Count By Server",
   "type": "timeseries",
   "description": "Tablet counts for selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(spanner_server) (spanner_paxos_tablet_count{job=\"spanner\", spanner_server=~\"$SpannerServer\"})",
     "legendFormat": "{{spanner_zone}} {{spanner_server}}"
    }
   ]
  },
  {
   "title": "Leader Count By Zone",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(spanner_zone) (spanner_paxos_tablet_count{job=\"spanner\", paxos_state=\"LeaderRunning\"})",
     "legendFormat": "{{spanner_zone}}"
    }
   ]
  },
  {
   "title": "Leader Count By Server",
   "type": "timeseries",
   "description": "Leader count for selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(spanner_server) (spanner_paxos_tablet_count{job=\"spanner\", paxos_state=\"LeaderRunning\", spanner_server=~\"$SpannerServer\"})",
     "legendFormat": "{{spanner_zone}}"
    }
   ]
  },
  {
   "title": "Unassigned Tablets Per Zone",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(spanner_zone) (spanner_zonemaster_unassigned_tablets_by_database_and_type{job=\"spanner\"})",
     "legendFormat": "{{spanner_zone}}"
    }
   ]
  },
  {
   "title": "Tablet Loads By Zone",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(spanner_zone) (rate(spanner_zonemaster_tablet_loads{job=\"spanner\"}[$__rate_interval]))",
     "legendFormat": "{{spanner_zone}}"
    }
   ]
  },
  {
   "title": "Tablet Unloads By Zone By Reason",
   "type": "timeseries",
   "description": "Rate of tablet unloads per zone per reason",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(spanner_zone, reason) (rate(spanner_zonemaster_tablet_unloads{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[$__rate_interval]))",
     "legendFormat": "{{spanner_zone}} {{reason}}"
    }
   ]
  },
  {
   "title": "Max Tablet Load For Each Server",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "max by(spanner_server) (spanner_server_tablet_compute_max{job=\"spanner\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hot Tablets Count",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(spanner_server_tablet_compute_distribution_count{job=\"spanner\", spanner_server=~\"$SpannerServer\"}) - sum(spanner_server_tablet_compute_distribution_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\", le=\"5766.503906\"})",
     "legendFormat": "Hot Tablets"
    }
   ]
  },
  {
   "title": "Tablet Load Distribution ",
   "type": "timeseries",
   "description": "Distribution of per tablet compute load  aggregated across selected servers.\nPercentiles values are approximation based on distribution metric. \nMAX value is exact.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (spanner_server_tablet_compute_distribution_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (spanner_server_tablet_compute_distribution_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}))",
     "legendFormat": "P90"
    },
    {
     "expr": "max(spanner_server_tablet_compute_max{job=\"spanner\", spanner_server=~\"$SpannerServer\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Tablets In Pushback Per Type Per Level",
   "type": "timeseries",
   "description": "Tablets in pushback per type per level across selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by(level, type) (spanner_server_tablet_pushback{job=\"spanner\", spanner_server=~\"$SpannerServer\"})",
     "legendFormat": "{{type}} {{level}}"
    }
   ]
  },
  {
   "title": "Tablets In Pushback Per Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum by(spanner_server) (spanner_server_tablet_pushback{job=\"spanner\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tablets Stack Depth Distribution",
   "type": "timeseries",
   "description": "Distribution of tablet stack depth across the selected servers.\nThe percentile value is not exact but an approximation derived from the histogram metric assuming uniform distribution within a histogram bucket.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (spanner_server_stack_depth_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (spanner_server_stack_depth_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (spanner_server_stack_depth_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Tablets Stack Depth (P50 Estimate) Per Locality Group",
   "type": "timeseries",
   "description": "P50 of tablet stack depth per locality group across selected servers.\nThe percentile value is not exact but an approximation derived from the histogram metric assuming uniform distribution within a histogram bucket.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, locality_group) (spanner_server_stack_depth_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tablets Stack Depth (P90 Estimate) Per Locality Group",
   "type": "timeseries",
   "description": "P90 of tablet stack depth per locality group across selected servers.\nThe percentile value is not exact but an approximation derived from the histogram metric assuming uniform distribution within a histogram bucket.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, locality_group) (spanner_server_stack_depth_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tablets Stack Depth (P99 Estimate) Per Locality Group",
   "type": "timeseries",
   "description": "P99 of tablet stack depth per locality group across selected servers.\nThe percentile value is not exact but an approximation derived from the histogram metric assuming uniform distribution within a histogram bucket.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, locality_group) (spanner_server_stack_depth_bucket{job=\"spanner\", spanner_server=~\"$SpannerServer\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Values Per Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(spanner_server) (last_over_time(spanner_server_size_stats_values{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[6m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Values Per Database",
   "type": "timeseries",
   "description": "Values per database across selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(database) (last_over_time(spanner_server_size_stats_values{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[6m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deletes Per Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(spanner_server) (last_over_time(spanner_server_size_stats_deletes{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[6m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deletes Per Database",
   "type": "timeseries",
   "description": "Deletes per database across selected servers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(database) (last_over_time(spanner_server_size_stats_deletes{job=\"spanner\", spanner_server=~\"$SpannerServer\"}[6m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}