{
 "title": "Spanner TrueTime",
 "description": "Metrics about Spanner TrueTime",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "TrueTime Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(spanner_server) (true_time_is_available{job=\"spanner\"})",
     "legendFormat": "{{spanner_server}}"
    }
   ]
  },
  {
   "title": "P99 TrueTime Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(spanner_server, le) (delta(true_time_drift_bucket{job=\"spanner\"}[5m])))",
     "legendFormat": "{{spanner_server}}"
    }
   ]
  },
  {
   "title": "P99 TrueTime Interval Uncertainty",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(spanner_server, le) (delta(true_time_interval_uncertainty_bucket{job=\"spanner\"}[5m])))",
     "legendFormat": "{{spanner_server}}"
    }
   ]
  },
  {
   "title": "VM Migration Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "vm_migration_count{job=\"spanner\"}",
     "legendFormat": "{{spanner_server}}"
    }
   ]
  },
  {
   "title": "Clock SLA Violations by Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(spanner_server) (rate(sla_tester_violation_count{job=\"spanner\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Whether this VM is violating Clock SLA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(spanner_server) (sla_tester_is_violator{job=\"spanner\"})",
     "legendFormat": "{{spanner_server}}"
    }
   ]
  }
 ]
}